version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: piepay
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/piepay
      MODE: ${MODE:-production}
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npx prisma generate && if [ \"$MODE\" = 'dev' ]; then npm run start:dev; else node dist/main.js; fi"
volumes:
  db_data: 